name: Deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:

env:
  WEBAPP_NAME: babatoobin_II    # set this to your application's name
 
  DOTNET_VERSION: '8.0.x'             # set this to the dot net version to use
  OUTPUTDIR: 'out'

jobs:
  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

     
    environment: dev
    steps:

      # Checkout the repo
      - uses: actions/checkout@v3
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build
      - name: dotnet build
        run: |
          dotnet restore
          dotnet build --configuration Release
          
      # Run dotnet publish    
      - name: Publish
        run: dotnet publish -c Release --property PublishDir=${{ env.OUTPUTDIR }} 
  
      - name: Copy files to the server
      
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "${{ env.OUTPUTDIR }}/*"
          target: "/babs.spooch.co.uk" 
