name: Deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  WEBAPP_NAME: babatoobin_II    # set this to your application's name
  PACKAGE_PATH: 'babs.spooch.co.uk'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'             # set this to the dot net version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:

      # Checkout the repo
      - uses: actions/checkout@v3
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          #dotnet publish -c Release --property PublishDir=${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp 
      - name: Publish
        run: dotnet publish -c Release -o out
  
      - name: Copy files to the server
      
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          #port: ${{ secrets.PORT }}
          source: "out/*"
          target: "/babs.spooch.co.uk"    

