name: test deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:

env:
  WEBAPP_NAME: babatoobin_II    # set this to your application's name
 
  DOTNET_VERSION: '8.0.x'       # set this to the dot net version to use
  OUTPUTDIR: 'out'

jobs:
  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
  deploy:
      name: deploy artifact
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v4
  
      - run: echo hello > world.txt
  
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: world.txt
  
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: distfiles
  
      - name: copy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host:  5.77.41.136
          username: spoochco
          password: a^1!8mk8YYG6X
          port: 21
          source: distfiles/*
          target: /babs.spooch.co.uk
